export const products = [
  {
    id: 1,
    name: 'Laptop ASUS XYZ',
    harga: 12000000,
    category: 'Electronics',
    quantity: 0,
  },
  {
    id: 2,
    name: 'Kamera Canon ABC',
    harga: 5000000,
    category: 'Electronics',
    quantity: 0,
  },
  { id: 3, name: 'Meja Kayu Solid', harga: 800000, category: 'Furniture', quantity: 0 },
  {
    id: 4,
    name: 'Smartphone Samsung Galaxy',
    harga: 6000000,
    category: 'Electronics',
    quantity: 0,
  },
  {
    id: 5,
    name: 'Pakaian T-Shirt Basic',
    harga: 150000,
    category: 'Fashion',
    quantity: 0,
  },
  {
    id: 6,
    name: 'Sepatu Sneakers Casual',
    harga: 300000,
    category: 'Fashion',
    quantity: 0,
  },
  {
    id: 7,
    name: 'Buku Panduan JavaScript',
    harga: 120000,
    category: 'Books',
    quantity: 0,
  },
  {
    id: 8,
    name: 'Mouse Gaming Logitech',
    harga: 400000,
    category: 'Electronics',
    quantity: 0,
  },
  {
    id: 9,
    name: 'Set Alat Masak Stainless',
    harga: 250000,
    category: 'Home and Kitchen',
    quantity: 0,
  },
  { id: 10, name: 'Bola Sepak Adidas', harga: 100000, category: 'Sports', quantity: 0 },
  { id: 11, name: 'Jaket Kulit Pria', harga: 900000, category: 'Fashion', quantity: 0 },
  { id: 12, name: 'Kursi Ergonomis', harga: 600000, category: 'Furniture', quantity: 0 },
  {
    id: 13,
    name: 'TV LED 50 Inch',
    harga: 4500000,
    category: 'Electronics',
    quantity: 0,
  },
  {
    id: 14,
    name: 'Celana Jeans Slim Fit',
    harga: 200000,
    category: 'Fashion',
    quantity: 0,
  },
  {
    id: 15,
    name: 'Printer Multifungsi',
    harga: 800000,
    category: 'Electronics',
    quantity: 0,
  },
  {
    id: 16,
    name: 'Lampu Gantung Minimalis',
    harga: 350000,
    category: 'Home and Kitchen',
    quantity: 0,
  },
  {
    id: 17,
    name: 'Gitar Akustik',
    harga: 1200000,
    category: 'Musical Instruments',
    quantity: 0,
  },
  { id: 18, name: 'Jam Tangan Fashion', harga: 180000, category: 'Fashion', quantity: 0 },
  { id: 19, name: 'Mainan Edukasi Anak', harga: 100000, category: 'Toys', quantity: 0 },
  {
    id: 20,
    name: 'Sprei King Size',
    harga: 300000,
    category: 'Home and Kitchen',
    quantity: 0,
  },
  {
    id: 21,
    name: 'Botol Minum Stainless',
    harga: 75000,
    category: 'Home and Kitchen',
    quantity: 0,
  },
  {
    id: 22,
    name: 'Earphone Bluetooth',
    harga: 200000,
    category: 'Electronics',
    quantity: 0,
  },
  { id: 23, name: 'Buku Resep Masakan', harga: 85000, category: 'Books', quantity: 0 },
  { id: 24, name: 'Baju Renang Anak', harga: 120000, category: 'Fashion', quantity: 0 },
  {
    id: 25,
    name: 'Keyboard Gaming RGB',
    harga: 350000,
    category: 'Electronics',
    quantity: 0,
  },
  {
    id: 26,
    name: 'Kasur Spring Bed King Size',
    harga: 1500000,
    category: 'Furniture',
    quantity: 0,
  },
  { id: 27, name: 'Dompet Kulit Asli', harga: 180000, category: 'Fashion', quantity: 0 },
  {
    id: 28,
    name: 'Speaker Bluetooth Portable',
    harga: 300000,
    category: 'Electronics',
    quantity: 0,
  },
  {
    id: 29,
    name: 'Keranjang Pakaian Laundry',
    harga: 90000,
    category: 'Home and Kitchen',
    quantity: 0,
  },
  { id: 30, name: 'Skateboard Anak', harga: 250000, category: 'Sports', quantity: 0 },
];
